package com.asiainfo.ctc.eda.Mail;

import java.awt.event.KeyEvent;
import java.util.ArrayList;

public class MainFrame extends javax.swing.JFrame {  
	  
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	ArrayList<String> list=new ArrayList<String>();  
    String s="";  
    int i;  
    /** Creates new form MainFrame */  
    public MainFrame() {  
        initComponents();  
        this.setTitle("自动排版功能");  
    }  
  
    /** This method is called from within the constructor to 
     * initialize the form. 
     * WARNING: Do NOT modify this code. The content of this method is 
     * always regenerated by the Form Editor. 
     */  
    // <editor-fold defaultstate="collapsed" desc="Generated Code">  
    private void initComponents() {  
  
        jScrollPane1 = new javax.swing.JScrollPane();  
        jTextArea1 = new javax.swing.JTextArea();  
        jButton1 = new javax.swing.JButton();  
        jScrollPane2 = new javax.swing.JScrollPane();  
        jTextArea2 = new javax.swing.JTextArea();  
  
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);  
  
        jScrollPane1.setName("jScrollPane1"); // NOI18N  
  
        jTextArea1.setColumns(20);  
        jTextArea1.setEditable(false);  
        jTextArea1.setLineWrap(true);  
        jTextArea1.setRows(5);  
        jTextArea1.setName("jTextArea1"); // NOI18N  
        jScrollPane1.setViewportView(jTextArea1);  
  
        jButton1.setText("提交");  
        jButton1.setName("jButton1"); // NOI18N  
        jButton1.addActionListener(new java.awt.event.ActionListener() {  
            public void actionPerformed(java.awt.event.ActionEvent evt) {  
                jButton1ActionPerformed(evt);  
            }  
        });  
  
        jScrollPane2.setName("jScrollPane2"); // NOI18N  
  
        jTextArea2.setColumns(20);  
        jTextArea2.setLineWrap(true);  
        jTextArea2.setRows(5);  
        jTextArea2.setName("jTextArea2"); // NOI18N  
        jTextArea2.addKeyListener(new java.awt.event.KeyAdapter() {  
            public void keyPressed(java.awt.event.KeyEvent evt) {  
                jTextArea2KeyPressed(evt);  
            }  
        });  
        jScrollPane2.setViewportView(jTextArea2);  
  
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());  
        getContentPane().setLayout(layout);  
        layout.setHorizontalGroup(  
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)  
            .addGroup(layout.createSequentialGroup()  
                .addGap(30, 30, 30)  
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)  
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)  
                    .addGroup(layout.createSequentialGroup()  
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)  
                        .addGap(30, 30, 30)  
                        .addComponent(jButton1)))  
                .addContainerGap(34, Short.MAX_VALUE))  
        );  
        layout.setVerticalGroup(  
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)  
            .addGroup(layout.createSequentialGroup()  
                .addContainerGap()  
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)  
                .addGap(18, 18, 18)  
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)  
                    .addComponent(jButton1)  
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))  
                .addGap(30, 30, 30))  
        );  
  
        pack();  
    }// </editor-fold>  
  
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {  
        // TODO add your handling code here:  
        System.out.println("enter/n");  
        jTextArea1.setText("");  
        String temp=jTextArea2.getText().trim();  
        int k=temp.indexOf(s);  
        list.add(temp.substring(k+s.length()));  
        for(int m=0;m<list.size();m++)  
        {  
            jTextArea1.append(list.get(m)+"/n");  
        }  
        jTextArea2.setText("");  
        list.clear();  
        s="";  
    }  
  
    private void jTextArea2KeyPressed(java.awt.event.KeyEvent evt) {  
        // TODO add your handling code here:  
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)  
        {  
            System.out.println("enter1/n");  
            String temp=jTextArea2.getText().trim();  
            int i;  
            if(s.equals(""))  
            {  
                s=temp;  
                list.add(s);  
            }  
            else  
            {  
                System.out.println(s);  
                i=temp.indexOf(s);  
                list.add(temp.substring(i+s.length()));  
                s=temp;  
            }  
        }  
    }  
  
    /** 
    * @param args the command line arguments 
    */  
    public static void main(String args[]) {  
        java.awt.EventQueue.invokeLater(new Runnable() {  
            public void run() {  
                new MainFrame().setVisible(true);  
            }  
        });  
    }  
  
    // Variables declaration - do not modify  
    private javax.swing.JButton jButton1;  
    private javax.swing.JScrollPane jScrollPane1;  
    private javax.swing.JScrollPane jScrollPane2;  
    private javax.swing.JTextArea jTextArea1;  
    private javax.swing.JTextArea jTextArea2;  
    // End of variables declaration  
  
}
